# Generated by Django 5.2.1 on 2025-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperequest',
            name='filter_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scraperequest',
            name='filter_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
